from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional

from jinja2 import Template

from backend.core.config import settings
from backend.core.logger import logger
from backend.core.security import generate_api_key, hash_token


_SLUG_RE = re.compile(r"[^a-z0-9-]+")

_APP_TEMPLATE = Template(
    """\"\"\"Auto-generated Kensei deployment for model_id={{ model_id }} slug={{ slug }}.\"\"\"
from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Optional

import cloudpickle
import pandas as pd
from fastapi import FastAPI, Header, HTTPException
from pydantic import BaseModel

MODEL_PATH = Path(__file__).parent / "model.pkl"
FEATURE_NAMES = {{ feature_names | tojson }}
ALGORITHM = "{{ algorithm }}"
TASK_TYPE = "{{ task_type }}"
SLUG = "{{ slug }}"

_model = None


def _get_model():
    global _model
    if _model is None:
        with MODEL_PATH.open("rb") as f:
            _model = cloudpickle.load(f)
    return _model


class PredictIn(BaseModel):
    rows: List[Dict[str, Any]]


class PredictOut(BaseModel):
    predictions: List[Any]
    probabilities: Optional[List[List[float]]] = None
    model_slug: str
    algorithm: str


app = FastAPI(title="Kensei Deployment: {{ slug }}", version="1.0")


@app.get("/health")
def health() -> Dict[str, str]:
    return {"status": "ok", "slug": SLUG, "algorithm": ALGORITHM}


@app.post("/predict", response_model=PredictOut)
def predict(payload: PredictIn, x_api_key: Optional[str] = Header(default=None, alias="X-API-Key")) -> PredictOut:
    if not payload.rows:
        raise HTTPException(status_code=400, detail="rows must be non-empty")
    df = pd.DataFrame(payload.rows)
    for col in FEATURE_NAMES:
        if col not in df.columns:
            df[col] = None
    df = df[FEATURE_NAMES]
    model = _get_model()
    try:
        preds = model.predict(df).tolist()
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"prediction failed: {e}")
    proba = None
    if TASK_TYPE == "classification" and hasattr(model.named_steps.get("model", model), "predict_proba"):
        try:
            proba = model.predict_proba(df).tolist()
        except Exception:
            proba = None
    return PredictOut(predictions=preds, probabilities=proba, model_slug=SLUG, algorithm=ALGORITHM)
"""
)

_README_TEMPLATE = Template(
    """# Kensei Deployment — {{ slug }}

Auto-generated by Kensei for model `{{ algorithm }}` ({{ task_type }}).

## Run locally
```bash
pip install fastapi uvicorn pandas cloudpickle scikit-learn
uvicorn app:app --host 0.0.0.0 --port 8080
```

## Predict
```bash
curl -X POST http://localhost:8080/predict \\
  -H "Content-Type: application/json" \\
  -H "X-API-Key: <your-key>" \\
  -d '{"rows": [{ {{ example_feature }} }]}'
```

Features expected (in order):
{% for f in feature_names %}- `{{ f }}`
{% endfor %}
"""
)


@dataclass
class GeneratedDeployment:
    slug: str
    output_dir: Path
    app_file: Path
    model_file: Path
    api_key_plain: Optional[str]
    api_key_hash: Optional[str]
    api_key_prefix: Optional[str]
    endpoint: str


def _slugify(name: str) -> str:
    s = name.strip().lower().replace("_", "-").replace(" ", "-")
    s = _SLUG_RE.sub("", s)
    s = re.sub(r"-+", "-", s).strip("-")
    return s or "deployment"


def _copy_model(artifact_path: str, out_dir: Path) -> Path:
    src = Path(artifact_path)
    dst = out_dir / "model.pkl"
    dst.write_bytes(src.read_bytes())
    return dst


def generate(
    model_id: int,
    slug: Optional[str],
    algorithm: str,
    task_type: str,
    feature_names: List[str],
    artifact_path: str,
    create_api_key: bool = True,
) -> GeneratedDeployment:
    final_slug = _slugify(slug) if slug else f"model-{model_id}"
    out_dir = settings.ARTIFACTS_DIR / "deployments" / final_slug
    out_dir.mkdir(parents=True, exist_ok=True)

    example_feature = ", ".join(f'"{n}": 0' for n in feature_names[:3])
    app_src = _APP_TEMPLATE.render(
        model_id=model_id,
        slug=final_slug,
        feature_names=feature_names,
        algorithm=algorithm,
        task_type=task_type,
    )
    readme_src = _README_TEMPLATE.render(
        slug=final_slug,
        algorithm=algorithm,
        task_type=task_type,
        feature_names=feature_names,
        example_feature=example_feature,
    )
    app_file = out_dir / "app.py"
    app_file.write_text(app_src, encoding="utf-8")
    (out_dir / "README.md").write_text(readme_src, encoding="utf-8")
    model_file = _copy_model(artifact_path, out_dir)

    api_key_plain: Optional[str] = None
    api_key_hash: Optional[str] = None
    api_key_prefix: Optional[str] = None
    if create_api_key:
        api_key_plain = generate_api_key()
        api_key_hash = hash_token(api_key_plain)
        api_key_prefix = api_key_plain.split("_", 1)[0]

    endpoint = f"/api/deployments/{final_slug}/predict"
    logger.info(f"deployment: generated {final_slug} at {out_dir}")
    return GeneratedDeployment(
        slug=final_slug,
        output_dir=out_dir,
        app_file=app_file,
        model_file=model_file,
        api_key_plain=api_key_plain,
        api_key_hash=api_key_hash,
        api_key_prefix=api_key_prefix,
        endpoint=endpoint,
    )
